[project]
name = "lerobot_teleoperator_rokae"
version = "0.1.0"
description = "LeRobot plugin for Rokae robots"
requires-python = ">=3.10"

dependencies = [
    "lerobot",
    "rokae_python_wrapper",
    "pyspacemouse",
    "pin-pink",
    "qpsolvers[open_source_solvers]",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["lerobot_teleoperator_rokae*"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
